# -*- coding: utf-8 -*-
"""Conquer_logica_lidifaria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ATExBEPttciENUNAyfGNoLBqXVX_SgAI
"""

# EXERCICIO: CALCULE A CONTA DO RESTAURANTE 

import math

math.sqrt(4)

#HORA DE CALCULAR OS DADOS DA CONTA

pedidos = [
  {"prato": "PF de frango", "valor": 25},
  {"prato": "Macarrão a bolonhesa", "valor": 22},
  {"prato": "PF de bife", "valor": 28},
  {"prato": "Batata frita", "valor": 20}
]

pessoas = ["João", "Maria", "Pedro", "Silvana"]

valor = 0

for pedido in pedidos:
  valor = valor + pedido ["valor"]

quantidade = len (pessoas)

def calcular_valor_pessoa (quantidade_pessoas, valor_total):
  return valor_total / quantidade_pessoas

valor_por_pessoa = calcular_valor_pessoa (quantidade, valor)

# RESULTADO
print ("Obrigada pela preferência! Aqui está sua conta:")
print ("Itens pedidos:", len (pedidos))
print ("Quantidade de pessoas:", len (pessoas))
print ("valor total da conta:", (valor))
print ("O valor por pessoa é:", valor_por_pessoa)